### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [open-policy-agent/opa#5382]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stage 1, 2 & 3 (no code or config changes necessary)

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-JNBNV64PDX`**
- [x] Configure GA4 website ID ([gtag.js]) through [Netlify snippet injection], "Google Analytics 4 - only in production", just before `</head>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-JNBNV64PDX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-JNBNV64PDX');
  </script>
  {% endif %}
  ```
- [x] Confirm that the GA4 site tag is receiving events

### Followup

- Confirm that the UA site tag is still receiving events -- CNCF doesn't have access to the UA analytics account, but there have been no code changes, so the site tag should still be receiving events.
- #5384

### Pre-migration analytics info for the website

- UA ID `UA-84550302-1` is registered via the old `analytics.js`
- Site built with Hugo 0.88.x
- Hosted on Netlify

/cc @caniszczyk @nate-double-u

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Hello maintainers: I can't seem to find the Netlify account under the sites accessible to the CNCF. Can you grant me access (my GitHub ID at cncf.io) to:

- OPA's Netlify account
- Google Analytics account for UA ID `UA-84550302-1`

**Comment by srenatus** [comment]
Heya! I'm happy to help set you up.

What I don't quite understand is the need to access OPA's Netlify account. The website is built from any merged pull request, and the GA stuff is no exception: 

https://github.com/open-policy-agent/opa/blob/main/docs/website/layouts/partials/google-analytics.html#L3

**Comment by srenatus** [comment]
✔️ Went ahead and sent you an invite to the netlify site: 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/870638/201639661-1de43cba-4727-4417-87d5-cd87a94f87cb.png">

**Comment by chalin** [comment]
> What I don't quite understand is the need to access OPA's Netlify account.

Thanks for access to the Netlify account @srenatus. Now that I've assessed the situation, I can confirm that the simplest way to upgrade to GA4 for the OPA website, is to use [Netlify snippet injection]. For task details, see the opening comment.

Can you also grant me access to the Google Analytics for the UA property `UA-84550302-1`? This isn't strictly necessary, but it will allow me to cross-check some of the cleanup tasks.

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by srenatus** [comment]
@peteroneilljr could you please do that GA user thing? I'm pretty illiterate when it comes to GA... 😳

**Comment by chalin** [comment]
GA4 setup is complete, so I'll close this issue. We'll track cleanup tasks via:

- #5384

**Comment by srenatus** [comment]
For future reference, this

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/870638/202429116-fb4b8445-8de8-4472-a34a-11f577bd04e7.png">


caused this:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/870638/202429045-4460354c-fb8f-4370-9180-59a1f3168e53.png">

**Comment by chalin** [comment]
> @peteroneilljr could you please do that GA user thing? I'm pretty illiterate when it comes to GA... 😳

@peteroneilljr @srenatus - I still need access to the old GA account; or, if you have access you need to opt out of Google's automatic creation of a new GA4 site tag, since we have one already.

**Comment by chalin** [comment]
For context, see:

- https://github.com/cncf/techdocs/issues/170
